### ISSUE TITLE
hts_QWindowTrim output problem

### ISSUE THREAD

**Issue by gjospin** [ibest/HTStream#147] opened 2018-12-19 20:56 UTC
Hello,
I tried using hts_QWindowTrim and looking through hts_QWindowTrimINTER.fastq, it seems like there is a problem with the formatting in the output. 
When I copy the problematic read (displayed below) to its own file, the output file is formatted correctly. 
As far as I can tell, there does not seem to be a problem with the input file, but it's so large, maybe I am missing something.

I used the following command 
`hts_QWindowTrim` -I 3300013857_1022686.7307.1.65714.TGACC.fastq -i

Input read:
@MISEQ03:189:000000000-A5290:1:2114:15705:28352 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAGACGGAGACAGCGCATTAATATTATCAAGCCACATCCGTGACCCAATCGATACGAAAGCACCACACATTTACACACTCCTCGCAACGACGCCAGACCCGACAAGCACAACTCTGAACACACCACACTGACAAACATCAC
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?1?//?DC###################################################################################################################################
@MISEQ03:189:000000000-A5290:1:2114:15705:28352 2:N:0:TGACC
GATGGGGAGAGCGGCGGGGTGGGGAAAAGCGGAGATCTCGGGGGGCGGCGGGAACTTAAAAAAAAAAAACAAAAGAAAGCAAACGCTCCGAACGAAAATGCCGCGCCATTTACACAAGACTTTCTTCAACGATAAACATAGCCAAAGGGAGCGATCGGCGACGAATCTCAAATAGCGTACCACAACCACACCCACACGCAACCACTAGCCAAAGCATGCCACGTCAGCCACCCAACTAGCGCTCAGCGACC
+
1111111111111A0AAE#########################################################################################################################################################################################################################################

Output:

@MISEQ03:189:000000000-A5290:1:2114:15705:28352 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACAAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAAACGAATAAATTCACACGACAACTGCTCGCAAAGGTCAG
+
ABBBAABB@CFFGGGFEGGB2BDFGCGHGDGHHHD333ABBFFBHFAHHHGEGGHGHDGFHHG1GDA1E0EEE/////??//3?4444?43//<>B/1BB11//><B001<1?
TCTTCGCTCCATAATTATTG
+
ABAABFFFA3>AEFAFEGGFFGGHAGABEGHHHFGHGFEGGFAHDGF5FHHGHEFHHGH55FAEFGHFHF5FGG5EE10@FGDEGGHHGHFFFGGHHHHFHHFHHHHHHFFGFHHHFHGHGFHHHHHEBGGFFHHFHHGFHGFF?GFHGGHHEHHHGFHHFFGBGGHGHHHEGHGFGFDHBA1FB?<FGF1?.<.FAGG1>F11FGHHGGG=D0DGBB00==DDDDGH0DGC;.;.:CG:CC0;GC0C
@MISEQ03:189:000000000-A5290:1:1101:20870:6588 1:N:0:TGACC
GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTGAAAAAAAAAAAACAACAACAACCAAAATAA
+
ABBBBBBBBFFFGFGGGGGGGGHHHGHFHHHHHGHGHHHHHGHGHEFGHFHGGGHGFGHFFHHGHHHHGGEEEEE11?/?//?/?///?/333

**Comment by samhunter** [comment] 2018-12-31 19:57
Hi @gjospin,
I copied and pasted the Input you provided, but don't get the output you provided. I think this is the same behavior you are describing. Is there any way you could provide a small file (maybe ~3 reads) which can reproduce this issue?

Also, I did notice one thing, read2 is really poor quality in your example. In my test, hts_QWindowTrim is discarding read2 entirely using default settings. This breaks the interleaved format (only read1 is written out). This is a bug we hadn't found before. I would suggest using the "-n" (no orphan reads) switch to ensure that this doesn't happen.

**Comment by gjospin** [comment] 2018-12-31 20:20
Ah excellent thanks for the work around. 
Seems like you identified the issue. I was also suspicious of the second read.

Unless you really want to explore these particular reads, I’m satisfied to close this at your convenience.

**Comment by msettles** [comment] 2019-01-11 15:15
I'm pretty sure I know where the issue is in the code, just need to determine the correction. Closing will leave Sam's other issue open until fixed.

**Closed by msettles** 2019-01-11 15:15 UTC
